[package]
name = "collector"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
shared_data = {path = "../shared_data"}
sysinfo = { version = "0.30.12", features = ["apple-app-store"] }
